POST http://localhost:8081/dog
Content-Type: application/json

{
  "id": 19,
  "name": "Bertaa",
  "height": 12.1,
  "weight": 1
}

###
GET http://localhost:8081/dog/19
Accept: application/json


###
PUT http://localhost:8081/dog/19
Content-Type: application/json

{
  "name": "Sharik",
  "height": 24,
  "weight": 8
}

###
DELETE http://localhost:8081/dog/19
Content-Type: application/json